const ACTION_TYPE = {
  // COUNTER ACTION TYPES
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_SET_STEP: 'COUNTER_SET_STEP',
  // TODO ACTION TYPES
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
};

export default ACTION_TYPE;
